### PR TITLE
Slicersalt 2020 07 22 9eb7107 - Add SRep to SVA

### PR DESCRIPTION
**Pull request by yehan0223**
@vicory Feel feel to play with the updated SVA and let me know if there is any issue.
@bpaniagua fyi

### CODE REVIEW

**Comment by bpaniagua** [comment]
@allemangD can you please take care of this?

**Comment by yehan0223** [comment]
@allemangD here's the sample data you could use. Since two s-rep files have the same name, one of them will be overwritten in the SPV previewing and we have warnings for that, yet it does not affect the actual pca compuation. For your reference, we also have a draft of the blog post about it here: https://docs.google.com/document/d/18frZVXZe7P9AP7OVyhLuZmvwwrqNBEFj-q5Dc5c5od8/edit
[hippocampus01.zip](https://github.com/slicersalt/ShapeVariationAnalyzer/files/7048837/hippocampus01.zip)

**Comment by allemangD** [comment]
Everything is working well for me, and the blog post seems very clear.

I did encounter the known issue with the duplicate name. I also encountered an issue where, since the `xml` files contained absolute paths on Ye Han's machine, doing any analysis would raise errors from non-existant files, crashing the program. Replacing the paths for my machine was an easy fix.

    $ find . -name '*.xml' -exec sed -i "s-/home/yehan/Desktop/salt/hippocampi_57-$PWD-g" {} +

It might be good to add some error message for failure to load files, rather than simply crashing SALT; but I think that's out of scope for this PR.

Merging.

**Comment by bpaniagua** [comment]
Thank you so much, DAvid!

**Pull request merged**
